services:
    A5sys\MantisApiBundle\Services\ProjectVersionService:
        class: A5sys\MantisApiBundle\Services\ProjectVersionService
        arguments:
            - "@A5sys\\MantisApiBundle\\Services\\MantisClientService"
    A5sys\MantisApiBundle\Services\MantisClientService:
        class: A5sys\MantisApiBundle\Services\MantisClientService
        arguments:
            - '%mantis_api.url%'
            - '%mantis_api.login%'
            - '%mantis_api.password%'
            - '%mantis_api.verify_peer%'
            - '%mantis_api.verify_peer_name%'
            - '%mantis_api.allow_self_signed%'
    A5sys\MantisApiBundle\Services\IssueService:
        class: A5sys\MantisApiBundle\Services\IssueService
        arguments:
            - "@A5sys\\MantisApiBundle\\Services\\MantisClientService"
